version: "3"
services: 
  db: 
    build: .
    environment: 
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: 123
    image: "mysql:5.7"
    restart: always
  nodejs: 
    build: .
    environment: 
      MYSQL_DATABASE: database
      MYSQL_HOST: localhost
      MYSQL_PASSWORD: 123
      MYSQL_USER: marion
    ports: 
      - "4000:5000"